# syntax=docker/dockerfile:1

FROM node:20-alpine AS build
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

ARG VITE_TERMINAL_CONFIG_PATH
ARG VITE_TERMINAL_ID
ARG VITE_TERMINAL_SECRETO
ARG VITE_TERMINAL_JWT
ARG VITE_TERMINAL_CLAVE_PRIVADA
ARG VITE_PARENT_URL
ARG VITE_SIDECAR_URL

ENV VITE_TERMINAL_CONFIG_PATH=${VITE_TERMINAL_CONFIG_PATH}
ENV VITE_TERMINAL_ID=${VITE_TERMINAL_ID}
ENV VITE_TERMINAL_SECRETO=${VITE_TERMINAL_SECRETO}
ENV VITE_TERMINAL_JWT=${VITE_TERMINAL_JWT}
ENV VITE_TERMINAL_CLAVE_PRIVADA=${VITE_TERMINAL_CLAVE_PRIVADA}
ENV VITE_PARENT_URL=${VITE_PARENT_URL}
ENV VITE_SIDECAR_URL=${VITE_SIDECAR_URL}

RUN npm run build

FROM nginx:1.27-alpine AS final
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
